settings:
  debug: false
# Those messages are null safe so if they can't be read the plugin would use default ones automatically.
quickranked:
  already-in-fight: '&cТы уже в бою!'
  already-in-queue: '&cТы уже в очереди!'
  no-queue-found: '&cНет доступных очередей с игроками!'
  joined-queue: '&aТы присоединился к очереди: &e%kit%'
  queue-join-broadcast: '&r樂 &#C9E4DEИгрок &b<player> &#C9E4DEначал поиск с китом <kit>'
  notifications-enabled: '&#90FBFE✔ &#C9E4DEУведомления о поиске матчей &#90FBFEвключены'
  notifications-disabled: '&#FF6B6B✖ &#C9E4DEУведомления о поиске матчей &#FF6B6Bотключены'
message:
  invalid-placeholder: '&cINVALID PLACEHOLDER'
  invalid-kit: '&cKIT DOESN''T EXIST'
  invalid-party: '&cINVALID PARTY'
  party-member:
    # kept it empty so it doesnt appear when it's requested
    invalid:-player: ''
